// Generated by skill: restructure-expo-project — review before editing
import { Platform } from 'react-native'
import { z } from 'zod'

const envSchema = z.object({
	EXPO_PUBLIC_API_URL: z.string().url().optional(),
	NODE_ENV: z.enum(['development', 'production', 'test']).optional(),
})

export const env = envSchema.parse(process.env)

if (Platform.OS === 'android') {
	env.EXPO_PUBLIC_API_URL = env.EXPO_PUBLIC_API_URL?.replace('localhost', '10.0.2.2')
}
