// Generated by skill: restructure-expo-project — review before editing
import { z } from 'zod'

const envSchema = z.object({
	API_URL: z.string().url().optional(),
	NODE_ENV: z.enum(['development', 'production', 'test']).optional(),
})

export const env = envSchema.parse(process.env)
