// Minimal root layout — generated by skill adjustments
import '@/styles/global.css'
import { Toasts } from '@backpackapp-io/react-native-toast'
import { QueryClientProvider } from '@tanstack/react-query'
import { Stack } from 'expo-router'
import { StatusBar } from 'react-native'
import { GestureHandlerRootView } from 'react-native-gesture-handler'
import { KeyboardProvider } from 'react-native-keyboard-controller'
import 'react-native-reanimated'

import FontGuard from '@/guards/font-guard'
import { BottomSheetProvider, useBottomSheet } from '@/hooks/use-bottom-sheets'
import { queryClient } from '@/libs/react-query'

export { ErrorBoundary } from 'expo-router'

export const unstable_settings = {
	initialRouteName: 'index',
}

export default function RootLayout() {
	return (
		<FontGuard>
			<GestureHandlerRootView style={{ flex: 1 }}>
				<QueryClientProvider client={queryClient}>
					<StatusBar barStyle="dark-content" backgroundColor="transparent" translucent />
					<KeyboardProvider preload>
						<BottomSheetProvider>
							<RootLayoutNav />
							<Toasts overrideDarkMode={true} />
						</BottomSheetProvider>
					</KeyboardProvider>
				</QueryClientProvider>
			</GestureHandlerRootView>
		</FontGuard>
	)
}

function RootLayoutNav() {
	const { isBottomSheetOpen } = useBottomSheet()

	return (
		<Stack
			screenOptions={{
				headerShown: false,
				contentStyle: { overflow: isBottomSheetOpen ? 'hidden' : 'visible' },
			}}
		>
			<Stack.Screen name="index" />
		</Stack>
	)
}
