// Minimal root layout — generated by skill adjustments
import '@/styles/global.css'
import { Toasts } from '@backpackapp-io/react-native-toast'
import { QueryClientProvider } from '@tanstack/react-query'
import { Stack } from 'expo-router'
import { StatusBar, View } from 'react-native'
import { GestureHandlerRootView } from 'react-native-gesture-handler'
import { KeyboardProvider } from 'react-native-keyboard-controller'
import 'react-native-reanimated'
import * as SystemUI from 'expo-system-ui'
import { FontGuard } from '@/guards/font-guard'
import { AuthProvider } from '@/hooks/use-auth'
import { BottomSheetProvider, useBottomSheet } from '@/hooks/use-bottom-sheets'
import { queryClient } from '@/libs/react-query'

export { ErrorBoundary } from 'expo-router'

export default function RootLayout() {
	return (
		<FontGuard>
			<GestureHandlerRootView style={{ flex: 1 }}>
				<QueryClientProvider client={queryClient}>
					<StatusBar barStyle="light-content" backgroundColor="transparent" translucent />
					<KeyboardProvider preload>
						<BottomSheetProvider>
							<AuthProvider>
								<RootLayoutNav />
								<Toasts />
							</AuthProvider>
						</BottomSheetProvider>
					</KeyboardProvider>
				</QueryClientProvider>
			</GestureHandlerRootView>
		</FontGuard>
	)
}

function RootLayoutNav() {
	const { isBottomSheetOpen } = useBottomSheet()
	SystemUI.setBackgroundColorAsync('#0b0b0e')

	return (
		<Stack
			screenOptions={{
				headerShown: false,
				contentStyle: { backgroundColor: '#0b0b0e', overflow: isBottomSheetOpen ? 'hidden' : 'visible' },
			}}
		>
			<Stack.Screen name="index" />
			<Stack.Screen name="(auth)/signin" />
			<Stack.Screen name="(auth)/signup" />
			<Stack.Screen name="(app)" />
		</Stack>
	)
}
