// Generated by skill: restructure-expo-project — review before editing

import { Text, View } from 'react-native'
import { Icon } from '@/components/icon'

export default function Home() {
	return (
		<View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
			<Text>Hello World</Text>
			<View className="h-5 w-5 text-red-500">
				<Icon name="asterisk-1" className="size-5 h-5 w-5 text-red-500" />
			</View>
		</View>
	)
}
