// Generated by skill: restructure-expo-project — review before editing

import { Text, View } from 'react-native'
import StreamlineBulletListIcon from '@/components/icons/streamline/bullet-list'

export default function Home() {
	return (
		<View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }} className="text-red-500">
			<Text>Hello World</Text>
			<View className="h-5 w-5 text-red-500">
				<StreamlineBulletListIcon />
			</View>
		</View>
	)
}
